services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/traefik.yml:ro
      - ../traefik/dynamic:/dynamic:ro
    networks:
      - dmz
      - internal
