api:
  dashboard: true
  insecure: true   # disable in prod, use TLS

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /dynamic
    watch: true

log:
  level: INFO
